---
title: 'Final Project: Guidance Document'
author: "Maya Digirolamo, Shelby Krenn"
date: "Due April 30, 2019"
output: html_notebook
---

# Purpose

*This document is required to indicate where various requirements can be found within your Final Project Report Rmd.  You must* **indicate line numbers as they appear in your final Rmd document** *accompanying each of the following required tasks. Points will be deducted if line numbers are missing or differ signficantly from the submitted Final Rmd document.*  


# Final Project Requirements

### Joins (at least) two different data sources for analysis

*Description: Report includes meaningful contributions from (at least) two different data sources that are JOINED for the analysis*

(A) .Rmd Line number(s) for join operation: 

**Lines 95-103**

### Data Wrangling (5 of 6 required)

*Description: Clear demonstration of proficiency should include proper use of 5 out of the following 6 topics from class: (+) general purpose data wrangling--e.g., filter, select mutate, summarise, arrange, group_by, etc. (+) spread & gather to stack/unstack variables (+) regular expressions (+) user-defined functions (+) loops and control flow (+) vectorized functions like the `apply` family, `purrr::map` or `dplyr::do`*

(A) .Rmd Line number(s) for an example of general purpose data wrangling: 

**Lines 70-82**

(C) .Rmd Line number(s) for use of regular expressions: 

**Line 101**

(D) .Rmd Line number(s) for use of user-defined functions: 

**Lines 169-200**

(E) .Rmd Line number(s) for use of loops and/or control flow: 



(F) .Rmd Line number(s) for use of vectorized functions: 

**Lines 190-193**

### Data Visualization (all 4 required)

*Description: Clear demonstration of proficiency should include at least FOUR distinct and useful data visualizations that are relevant to purpose of the analysis. Include at least one effective visualization with layered data from distinct data structures--e.g., a `geom` that plots data from a secondary data frame AND another must effectively display many--3 or more--variables. All plots must demonstrate good plotting practices.*

(A) .Rmd Line number(s) for visualization with layered data from distinct data structures--e.g., a `geom` that plots data from a secondary data frame: 

**Lines 124-137**

(B) .Rmd Line number(s) for visualization displaying many--3 or more--variables (A, B, C, & D must be four **different** plots): 

**Lines 204-246**

(C) .Rmd Line number(s) for a third visualization: 

**Lines 87-89**

(D) .Rmd Line number(s) for a third visualization: 

**Lines 252-256**


### Data Analysis (3 of 5 required)

*Description: Clear demonstration of proficiency should include proper use of 3 out of the following 4 topics from class: (+) statistical modeling/supervised learning (+) unsupervised learning (+) user-defined simulations (+) analysis of text data (+) R tools for "big data"*

(A) .Rmd Line number(s) for statistical modeling/supervised learning: 

**Lines 107-120**


(C) .Rmd Line number(s) for user-defined simulation(s): 

**Lines 262-300**


(D) .Rmd Line number(s) for analysis of text data: 

**Lines 145-164**